/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Controlador.DuoLink.listadoIngles;
import static Controlador.DuoLink.listadoSignificado;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.io.*;
import java.util.Random;

//import com.sun.speech.freetts.*;
/**
 *
 * @author BOG-A408-E-016
 */
public class VentanaAprender extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAprender
     */
    public VentanaAprender() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jbutFrase = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtSignificado1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtFraseIngles1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbutPlay = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jtxtFraseIngles2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxtSignificado2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jbutPlay1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jtxtFraseIngles3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtSignificado3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jbutPlay2 = new javax.swing.JButton();
        jbutRegresar3 = new javax.swing.JButton();
        jbutListo = new javax.swing.JButton();
        jbutBorrar = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FRASE EN INGLES");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("APRENDER FRASE");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/22.PNG"))); // NOI18N

        jbutFrase.setBackground(new java.awt.Color(153, 0, 0));
        jbutFrase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutFrase.setForeground(new java.awt.Color(255, 255, 255));
        jbutFrase.setText("Frase");
        jbutFrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutFraseActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FRASE EN INGLES");

        jtxtSignificado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSignificado1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SIGNIFICADO");

        jtxtFraseIngles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFraseIngles1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRONUNCIACION");

        jbutPlay.setBackground(new java.awt.Color(153, 0, 0));
        jbutPlay.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jbutPlay.setForeground(new java.awt.Color(255, 255, 255));
        jbutPlay.setText("Play");
        jbutPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutPlayActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FRASE EN INGLES");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SIGNIFICADO");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PRONUNCIACION");

        jbutPlay1.setBackground(new java.awt.Color(153, 0, 0));
        jbutPlay1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jbutPlay1.setForeground(new java.awt.Color(255, 255, 255));
        jbutPlay1.setText("Play");
        jbutPlay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutPlay1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FRASE EN INGLES");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SIGNIFICADO");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PRONUNCIACION");

        jbutPlay2.setBackground(new java.awt.Color(153, 0, 0));
        jbutPlay2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jbutPlay2.setForeground(new java.awt.Color(255, 255, 255));
        jbutPlay2.setText("Play");
        jbutPlay2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutPlay2ActionPerformed(evt);
            }
        });

        jbutRegresar3.setBackground(new java.awt.Color(153, 0, 0));
        jbutRegresar3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutRegresar3.setForeground(new java.awt.Color(255, 255, 255));
        jbutRegresar3.setText("Regresar");
        jbutRegresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutRegresar3ActionPerformed(evt);
            }
        });

        jbutListo.setBackground(new java.awt.Color(153, 0, 0));
        jbutListo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutListo.setForeground(new java.awt.Color(255, 255, 255));
        jbutListo.setText("Listo");
        jbutListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutListoActionPerformed(evt);
            }
        });

        jbutBorrar.setBackground(new java.awt.Color(153, 0, 0));
        jbutBorrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jbutBorrar.setText("Borrar");
        jbutBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtFraseIngles2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                                    .addComponent(jtxtSignificado2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jbutPlay1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(44, 44, 44)
                                .addComponent(jtxtSignificado3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(20, 20, 20)
                                .addComponent(jtxtFraseIngles3, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(38, 38, 38)
                                .addComponent(jbutPlay2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(37, 37, 37)
                                .addComponent(jbutPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbutFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtFraseIngles1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                    .addComponent(jtxtSignificado1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jbutRegresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jbutBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jbutListo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbutFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFraseIngles1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtSignificado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jbutPlay))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFraseIngles2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtSignificado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jbutPlay1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFraseIngles3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtxtSignificado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jbutPlay2))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutRegresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutListo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutFraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutFraseActionPerformed

        Random r = new Random();
        int randomIndex = r.nextInt(listadoIngles.size());
        jtxtFraseIngles1.setText((String) listadoIngles.get(randomIndex));
        jtxtSignificado1.setText((String) listadoSignificado.get(randomIndex));
        
        int randomIndex2 = r.nextInt(listadoIngles.size());
        jtxtFraseIngles2.setText((String) listadoIngles.get(randomIndex2));
        jtxtSignificado2.setText((String) listadoSignificado.get(randomIndex2));
        
        int randomIndex3 = r.nextInt(listadoIngles.size());
        jtxtFraseIngles3.setText((String) listadoIngles.get(randomIndex3));
        jtxtSignificado3.setText((String) listadoSignificado.get(randomIndex3));
        
    }//GEN-LAST:event_jbutFraseActionPerformed

    private void jbutPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutPlayActionPerformed
        // TODO add your handling code here:
        Voice voice ;
        
        VoiceManager vm= VoiceManager.getInstance();
        
        voice =vm.getVoice(VOICENAME);
        
        voice.allocate();
        
        try
        {
            voice.speak(jtxtFraseIngles1.getText());
            
        }catch(Exception e)
                {
                    
                }
    }//GEN-LAST:event_jbutPlayActionPerformed

    private void jbutPlay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutPlay1ActionPerformed
        // TODO add your handling code here:
         Voice voice ;
        
        VoiceManager vm= VoiceManager.getInstance();
        
        voice =vm.getVoice(VOICENAME2);
        
        voice.allocate();
        
        try
        {
            voice.speak(jtxtFraseIngles2.getText());
            
        }catch(Exception e)
                {
                    
                }
    }//GEN-LAST:event_jbutPlay1ActionPerformed

    private void jbutPlay2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutPlay2ActionPerformed
        // TODO add your handling code here:
         Voice voice ;
        
        VoiceManager vm= VoiceManager.getInstance();
        
        voice =vm.getVoice(VOICENAME2);
        
        voice.allocate();
        
        try
        {
            voice.speak(jtxtFraseIngles3.getText());
            
        }catch(Exception e)
                {
                    
                }
    }//GEN-LAST:event_jbutPlay2ActionPerformed

    private void jbutRegresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutRegresar3ActionPerformed
        VentanaInicio Vi = new VentanaInicio();
        Vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbutRegresar3ActionPerformed

    private void jbutListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutListoActionPerformed
        // TODO add your handling code here:
        VentanaInicio Vi = new VentanaInicio();
        Vi.setVisible(true);
        this.dispose();                     
    }//GEN-LAST:event_jbutListoActionPerformed

    private void jbutBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutBorrarActionPerformed
        Borrar ();
    }//GEN-LAST:event_jbutBorrarActionPerformed

    private void jtxtFraseIngles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFraseIngles1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFraseIngles1ActionPerformed

    private void jtxtSignificado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSignificado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSignificado1ActionPerformed

    public void Borrar(){
        jtxtFraseIngles1.setText("");
        jtxtFraseIngles2.setText("");
        jtxtFraseIngles3.setText("");
        jtxtSignificado1.setText("");
        jtxtSignificado2.setText("");
        jtxtSignificado3.setText("");

   }
    
    private static final String VOICENAME="kevin16";
    private static final String VOICENAME1="kevin16";
    private static final String VOICENAME2="kevin16";
     private static final String VOICENAME3="kevin16";
    private static final String VOICENAME4="kevin16";
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAprender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAprender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAprender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAprender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAprender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbutBorrar;
    private javax.swing.JButton jbutFrase;
    private javax.swing.JButton jbutListo;
    private javax.swing.JButton jbutPlay;
    private javax.swing.JButton jbutPlay1;
    private javax.swing.JButton jbutPlay2;
    private javax.swing.JButton jbutRegresar3;
    private javax.swing.JTextField jtxtFraseIngles1;
    private javax.swing.JTextField jtxtFraseIngles2;
    private javax.swing.JTextField jtxtFraseIngles3;
    private javax.swing.JTextField jtxtSignificado1;
    private javax.swing.JTextField jtxtSignificado2;
    private javax.swing.JTextField jtxtSignificado3;
    // End of variables declaration//GEN-END:variables
}
