/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Controlador.DuoLink.listadoIngles;
import static Controlador.DuoLink.listadoSignificado;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author BOG-A408-E-017
 */
public class VentanaFrases extends javax.swing.JFrame {

    /**
     * Creates new form VentanaFrases
     */
    public VentanaFrases() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbutFrase = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtxtFraseEspañol = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtFraseIngles = new javax.swing.JTextField();
        jbutVerificar = new javax.swing.JButton();
        jbutBorrar = new javax.swing.JButton();
        jbutRegresar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/55.PNG"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TEST DE FRASES");

        jbutFrase.setBackground(new java.awt.Color(153, 0, 0));
        jbutFrase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbutFrase.setForeground(new java.awt.Color(255, 255, 255));
        jbutFrase.setText("Frase");
        jbutFrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutFraseActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FRASE EN ESPAÑOL");

        jtxtFraseEspañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFraseEspañolActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("¿COMO SERIA LA FRASE EN INGLES?");

        jtxtFraseIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFraseInglesActionPerformed(evt);
            }
        });

        jbutVerificar.setBackground(new java.awt.Color(153, 0, 0));
        jbutVerificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutVerificar.setForeground(new java.awt.Color(255, 255, 255));
        jbutVerificar.setText("Verificar");
        jbutVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutVerificarActionPerformed(evt);
            }
        });

        jbutBorrar.setBackground(new java.awt.Color(153, 0, 0));
        jbutBorrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jbutBorrar.setText("Borrar");
        jbutBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutBorrarActionPerformed(evt);
            }
        });

        jbutRegresar3.setBackground(new java.awt.Color(153, 0, 0));
        jbutRegresar3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutRegresar3.setForeground(new java.awt.Color(255, 255, 255));
        jbutRegresar3.setText("Regresar");
        jbutRegresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutRegresar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jbutFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtFraseEspañol, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtFraseIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jbutVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jbutBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jbutRegresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jbutFrase)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtFraseEspañol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtFraseIngles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutRegresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int randomIndex;
    private void jbutFraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutFraseActionPerformed
        Random r = new Random();
        randomIndex = r.nextInt(listadoSignificado.size());
        jtxtFraseEspañol.setText((String) listadoSignificado.get(randomIndex));
    }//GEN-LAST:event_jbutFraseActionPerformed
    
    
    
    private void jtxtFraseEspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFraseEspañolActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtFraseEspañolActionPerformed

    private void jtxtFraseInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFraseInglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFraseInglesActionPerformed

    private void jbutVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutVerificarActionPerformed
        String dato = jtxtFraseIngles.getText();
        String datoEnLista = (String) listadoIngles.get(randomIndex);
        System.out.println(datoEnLista);
        System.out.println(dato);
        if(dato.contains(datoEnLista)){
            JOptionPane.showMessageDialog(null, "La frase esta correcta.");
            Borrar();
        } else {
            JOptionPane.showMessageDialog(null, "Error. Porfavor verificar si esta escrito correctamente,"+"\n"+"si no es así, vuela a repasar.");
        }
        
    }//GEN-LAST:event_jbutVerificarActionPerformed

    private void jbutBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutBorrarActionPerformed
        jtxtFraseIngles.setText("");
        
    }//GEN-LAST:event_jbutBorrarActionPerformed

    private void jbutRegresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutRegresar3ActionPerformed
        VentanaInicio Vi = new VentanaInicio();
        Vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbutRegresar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFrases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFrases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFrases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFrases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFrases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutBorrar;
    private javax.swing.JButton jbutFrase;
    private javax.swing.JButton jbutRegresar3;
    private javax.swing.JButton jbutVerificar;
    private javax.swing.JTextField jtxtFraseEspañol;
    private javax.swing.JTextField jtxtFraseIngles;
    // End of variables declaration//GEN-END:variables

    private void Borrar() {
        jtxtFraseIngles.setText("");
        jtxtFraseIngles.setText("");    
    }
}
