/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Controlador.DuoLink.listadoIngles;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author BOG-A408-E-017
 */
public class VentanaPronunciacion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPronunciacion
     */
    public VentanaPronunciacion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbutPronunFrase = new javax.swing.JButton();
        jbutPlay = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtxtFraseIngles = new javax.swing.JTextField();
        jbutRegresar3 = new javax.swing.JButton();
        jbutBorrar = new javax.swing.JButton();
        jbutVerificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TEST PRONUNCIACION");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/33.PNG"))); // NOI18N

        jbutPronunFrase.setBackground(new java.awt.Color(153, 0, 0));
        jbutPronunFrase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbutPronunFrase.setForeground(new java.awt.Color(255, 255, 255));
        jbutPronunFrase.setText("Pronunciacion Frase");
        jbutPronunFrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutPronunFraseActionPerformed(evt);
            }
        });

        jbutPlay.setBackground(new java.awt.Color(153, 0, 0));
        jbutPlay.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jbutPlay.setForeground(new java.awt.Color(255, 255, 255));
        jbutPlay.setText("Play");
        jbutPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutPlayActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¿QUE DICE EL AUDIO?");

        jtxtFraseIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFraseInglesActionPerformed(evt);
            }
        });

        jbutRegresar3.setBackground(new java.awt.Color(153, 0, 0));
        jbutRegresar3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutRegresar3.setForeground(new java.awt.Color(255, 255, 255));
        jbutRegresar3.setText("Regresar");
        jbutRegresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutRegresar3ActionPerformed(evt);
            }
        });

        jbutBorrar.setBackground(new java.awt.Color(153, 0, 0));
        jbutBorrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jbutBorrar.setText("Borrar");
        jbutBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutBorrarActionPerformed(evt);
            }
        });

        jbutVerificar.setBackground(new java.awt.Color(153, 0, 0));
        jbutVerificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbutVerificar.setForeground(new java.awt.Color(255, 255, 255));
        jbutVerificar.setText("Verificar");
        jbutVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jbutPronunFrase, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(97, 97, 97)
                            .addComponent(jbutPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(52, 52, 52)
                            .addComponent(jLabel2))
                        .addComponent(jtxtFraseIngles, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jbutVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jbutBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jbutRegresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutPronunFrase)
                    .addComponent(jbutPlay))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jtxtFraseIngles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutRegresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int randomIndex;
    String frase;
    private void jbutPronunFraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutPronunFraseActionPerformed
        Random r = new Random();
        randomIndex = r.nextInt(listadoIngles.size());
        frase = (String) listadoIngles.get(randomIndex);
        System.out.println(frase);
        JOptionPane.showMessageDialog(null, "Pronunciacion cargada exitosamente."+"\n"+"Presione el botón Play.");
    }//GEN-LAST:event_jbutPronunFraseActionPerformed

    private void jbutPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutPlayActionPerformed
        // TODO add your handling code here:
         Voice voice ;
        
        VoiceManager vm= VoiceManager.getInstance();
        
        voice =vm.getVoice(VOICENAME);
        
        voice.allocate();
        
        try
        {
            voice.speak(frase);
            
        }catch(Exception e)
                {
                    
                }
    }//GEN-LAST:event_jbutPlayActionPerformed

    private void jbutRegresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutRegresar3ActionPerformed
        VentanaInicio Vi = new VentanaInicio();
        Vi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbutRegresar3ActionPerformed

    private void jbutBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutBorrarActionPerformed
        jtxtFraseIngles.setText("");
    }//GEN-LAST:event_jbutBorrarActionPerformed

    private void jbutVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutVerificarActionPerformed
        // TODO add your handling code here:
        String dato = jtxtFraseIngles.getText();
        String datoEnLista = (String) listadoIngles.get(randomIndex);
         if(dato.contains(datoEnLista)){
            JOptionPane.showMessageDialog(null, "La frase esta correcta.");
            jtxtFraseIngles.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Error. Porfavor verificar si esta escrito correctamente,"+"\n"+"si no es así, vuela a repasar.");
        }
        
    }//GEN-LAST:event_jbutVerificarActionPerformed

    private void jtxtFraseInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFraseInglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFraseInglesActionPerformed

    private static final String VOICENAME="kevin16";
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPronunciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPronunciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPronunciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPronunciacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPronunciacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbutBorrar;
    private javax.swing.JButton jbutPlay;
    private javax.swing.JButton jbutPronunFrase;
    private javax.swing.JButton jbutRegresar3;
    private javax.swing.JButton jbutVerificar;
    private javax.swing.JTextField jtxtFraseIngles;
    // End of variables declaration//GEN-END:variables
}
